### PR TITLE
Feature/#13194 supports urls with path variables in the http call flow step from http endpoint 

### PR DESCRIPTION
**Pull request by agreggio-slingr**
Pull-request for issue https://github.com/slingr-stack/platform/issues/13194 created by @agreggio-slingr

## What does it do?
Adds support for path variable in httpCall flow step

## How to test it?

1. Config a new http-endpoint 
2. Use http-endpoint and create an action with Action Type -> Flow
3. In the flow designer create a new generic flow with:
     method = Get
     url = https://test1.idea2.io/dev/runtime/api/data/contacts/:id
     Add a Path Variables  with key = id and value=5506fc44c2eee3b1a702694e
     Add a headers with key = token and value = o1ecfO0tRSpUc2HkLODTZF8DLgvfOU9G
     Apply and push changes
 
4. Go to runtime and launch action

### CODE REVIEW

**Comment by juaniorbegozo** [comment]
#approve

**Comment by sebasmoyano** [comment]
#approve

**Comment by sebasmoyano** [comment]
Are path variables created automatically after setting the URL?

**Comment by sebasmoyano** [comment]
Can you share a screenshot or video to see how the configuration looks like?

**Comment by agreggio-slingr** [comment]
> Are path variables created automatically after setting the URL?

No, it is necessary to enter them manually, understanding that the apiValue component created by Lautaro does not support this functionality.
There is a validation in the endpoint, which controls that if the url contains ":" it has its keyValue pair in the path variable.

**Comment by agreggio-slingr** [comment]
> Can you share a screenshot or video to see how the configuration looks like?

I can, this is an example configuration
Screenshot from 2022-12-30 15-52-17

**Comment by sebasmoyano** [comment]
> > Are path variables created automatically after setting the URL?
> 
> No, it is necessary to enter them manually, understanding that the apiValue component created by Lautaro does not support this functionality. There is a validation in the endpoint, which controls that if the url contains ":" it has its keyValue pair in the path variable.

OK, I think we should display the `Path variables` field only if it is at least one defined in the URL.

**Comment by agreggio-slingr** [comment]
> > > Are path variables created automatically after setting the URL?
> > 
> > 
> > No, it is necessary to enter them manually, understanding that the apiValue component created by Lautaro does not support this functionality. There is a validation in the endpoint, which controls that if the url contains ":" it has its keyValue pair in the path variable.
> 
> OK, I think we should display the `Path variables` field only if it is at least one defined in the URL.



> > > Are path variables created automatically after setting the URL?
> > 
> > 
> > No, it is necessary to enter them manually, understanding that the apiValue component created by Lautaro does not support this functionality. There is a validation in the endpoint, which controls that if the url contains ":" it has its keyValue pair in the path variable.
> 
> OK, I think we should display the `Path variables` field only if it is at least one defined in the URL.

The following parameters exist for a field of type text
"required": "config.url.includes(':')"
"visibility": ".config.url.includes(':')"

I did the test to implement it in a keyValue but it throws the following error.

`system.js:109` TypeError: Cannot read properties of undefined (reading `'includes')`

Please I would need help from the front end team to complete the task.

**Comment by sebasmoyano** [comment]
> complete

OK, @LautaroEscudero can you help with this?

**Comment by sebasmoyano** [comment]
> > > > Are path variables created automatically after setting the URL?
> > > 
> > > 
> > > No, it is necessary to enter them manually, understanding that the apiValue component created by Lautaro does not support this functionality. There is a validation in the endpoint, which controls that if the url contains ":" it has its keyValue pair in the path variable.
> > 
> > 
> > OK, I think we should display the `Path variables` field only if it is at least one defined in the URL.
> 
> > > > Are path variables created automatically after setting the URL?
> > > 
> > > 
> > > No, it is necessary to enter them manually, understanding that the apiValue component created by Lautaro does not support this functionality. There is a validation in the endpoint, which controls that if the url contains ":" it has its keyValue pair in the path variable.
> > 
> > 
> > OK, I think we should display the `Path variables` field only if it is at least one defined in the URL.
> 
> The following parameters exist for a field of type text "required": "config.url.includes(':')" "visibility": ".config.url.includes(':')"
> 
> I did the test to implement it in a keyValue but it throws the following error.
> 
> `system.js:109` TypeError: Cannot read properties of undefined (reading `'includes')`
> 
> Please I would need help from the front end team to complete the task.

I think you should check if `config.url` is a valid reference.

**Comment by sebasmoyano** [comment]
> Are path variables created automatically after setting the URL?

We should support autocomplete path variables once we implement the  `API call` in the `pandadoc` endpoint. We can have other components for the form generator framework.

**Comment by LautaroEscudero** [comment]
> > complete
> 
> OK, @LautaroEscudero can you help with this?

Sure, I can help.

**Comment by agreggio-slingr** [comment]
> > Are path variables created automatically after setting the URL?
> 
> We should support autocomplete path variables once we implement the `API call` in the `pandadoc` endpoint. We can have other components for the form generator framework.



> > Are path variables created automatically after setting the URL?
> 
> We should support autocomplete path variables once we implement the `API call` in the `pandadoc` endpoint. We can have other components for the form generator framework.

I understand that this would be a behavior of the dedicated endpoints which should be done in the task https://github.com/slingr-stack/platform/issues/13192 in the case of pandaDoc.
This is an example of how it would look like
Screenshot from 2022-12-30 17-03-27

**Comment by sebasmoyano** [comment]
> > > Are path variables created automatically after setting the URL?
> > 
> > 
> > We should support autocomplete path variables once we implement the `API call` in the `pandadoc` endpoint. We can have other components for the form generator framework.
> 
> > > Are path variables created automatically after setting the URL?
> > 
> > 
> > We should support autocomplete path variables once we implement the `API call` in the `pandadoc` endpoint. We can have other components for the form generator framework.
> 
> I understand that this would be a behavior of the dedicated endpoints which should be done in the task [slingr-stack/platform#13192](https://github.com/slingr-stack/platform/issues/13192) in the case of pandaDoc. This is an example of how it would look like Screenshot from 2022-12-30 17-03-27

Exactly!

**Comment by agreggio-slingr** [comment]
> > > complete
> > 
> > 
> > OK, @LautaroEscudero can you help with this?
> 
> Sure, I can help.

Resolve comment, with [feature](https://github.com/slingr-stack/platform/issues/13227)

**Comment by sebasmoyano** [comment]
#approve

**Pull request merged**
