### PR TITLE
#9 UI improvements for HTTP call step

### LINKED ISSUE #9: UI improvements for HTTP call step
- In the `Override settings` section there are some that are in the endpoint configuration, such as the Connection timeout or Read timeout, but there are others that are not, such as `Download` or `Full Response`. In the section to override settings we should put the options that are in the HTTP endpoint only. The other things should go in another section. Ideally, you would be able to define what things you want to overwrite instead of overwriting everything, but I understand the difficulty in that for now.
- Methods should be upper case. The default value should be `GET` (take a look at this commit https://github.com/slingr-stack/http-endpoint/commit/6988dff66d56917d85eb30f89900b10b78e0340a). 
- There are cases where we have help texts that do not add much to me, such as "Select method" or "Select event". If we have nothing to add to what is obvious, I would not put anything. We need to improve description for headers and params (you can check the commit https://github.com/slingr-stack/http-endpoint/commit/6988dff66d56917d85eb30f89900b10b78e0340a).
- When you don't have headers or params, you see that blank space. I think we could reduce it.
- This escapes a bit from what the endpoints are, but is more related to the configuration of the steps, but it would be nice if some settings could be grouped into sections and collapsed. For example, an `Advanced` section with settings that are not so common, so that the configuration is cleaner and not as intimidating.

### PR DESCRIPTION
**Pull request by pasaperez-work**
Pull-request for issue #9 created by @pasaperez-slingr

## What it does?

Some settings have been simplified from the generic flow step.
Fixed the labeling and description of the generic flow step inputs.
Reduced the input space of headers and query params of the generic flow step.
Grouped advanced settings.

## How to test it?

You can test it by creating a step of the generic flow step and seeing the changes in the UI.

## Implementation notes

N/A

## Deployment notes

There are no deployment notes

### CODE REVIEW

**Comment by pasaperez-work** [comment]
Linked Pull Request: https://github.com/slingr-stack/platform/pull/13502

**Comment by sebasmoyano** [comment]
#approve

**Comment by pasaperez-work** [comment]
image

**Comment by sebasmoyano** [comment]
> image

Looks good! Thanks!

**Comment by sebasmoyano** [comment]
@agreggio-slingr I'm going to merge this so it is available in the release.

**Pull request merged**
